services:
  postgres:
    image: postgres:latest
    container_name: cleanArch_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - cleanArch_network

volumes:
  pg_data:

networks:
  cleanArch_network:
    driver: bridge